In [60]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('/content/drive/MyDrive/gsearch_jobs.csv')

In [41]:
df_cleaning=df.copy()

In [42]:
df_cleaning.duplicated().sum()

np.int64(0)

In [43]:
df_cleaning.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61953 entries, 0 to 61952
Data columns (total 27 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Unnamed: 0           61953 non-null  int64
 1   index                61953 non-null  int64
 2   title                61953 non-null  object
 3   company_name         61953 non-null  object
 4   location             61916 non-null  object
 5   via                  61944 non-null  object
 6   description          61953 non-null  object
 7   extensions           61953 non-null  object
 8   job_id               61953 non-null  object
 9   thumbnail            38194 non-null  object
 10  posted_at            61763 non-null  object
 11  schedule_type        61707 non-null  object
 12  work_from_home       27980 non-null  object
 13  salary               10088 non-null  object
 14  search_term          61953 non-null  object
 15  date_time            61953 non-null  object
 16  search_location      61953 non-null  object
 17  commute_time         0 non-null      float64
 18  salary_pay           10088 non-null  object
 19  salary_rate          10088 non-null  object
 20  salary_avg           10088 non-null  float64
 21  salary_min           9512 non-null   float64
 22  salary_max           9512 non-null   float64
 23  salary_hourly        5900 non-null   float64
 24  salary_yearly        4069 non-null   float64
 25  salary_standardized  10088 non-null  float64
 26  description_tokens   61953 non-null  object
dtypes: float64(7), int64(2), object(18)
memory usage: 12.8+ MB

In [44]:
df_cleaning.isnull().sum().sort_values(ascending=False)

commute_time           61953
salary_yearly          57884
salary_hourly          56053
salary_max             52441
salary_min             52441
salary                 51865
salary_pay             51865
salary_rate            51865
salary_standardized    51865
salary_avg             51865
work_from_home         33973
thumbnail              23759
schedule_type            246
posted_at                190
location                  37
via                        9
index                      0
title                      0
Unnamed: 0                 0
extensions                 0
job_id                     0
company_name               0
description                0
date_time                  0
search_location            0
search_term                0
description_tokens         0
dtype: int64

In [45]:
df.head()

,Unnamed: 0,index,title,company_name,location,via,description,extensions,job_id,thumbnail,...,commute_time,salary_pay,salary_rate,salary_avg,salary_min,salary_max,salary_hourly,salary_yearly,salary_standardized,description_tokens
0,0,0,Data Analyst,Meta,Anywhere,via LinkedIn,In the intersection of compliance and analytic...,"['15 hours ago', '101K–143K a year', 'Work fro...",eyJqb2JfdGl0bGUiOiJEYXRhIEFuYWx5c3QiLCJodGlkb2...,https://encrypted-tbn0.gstatic.com/images?q=tb...,...,NaN,101K–143K,a year,122000.0,101000.0,143000.0,NaN,122000.0,122000.0,"['tableau', 'r', 'python', 'sql']"
1,1,1,Data Analyst,ATC,United States,via LinkedIn,Job Title: Entry Level Business Analyst / Prod...,"['12 hours ago', 'Full-time', 'Health insurance']",eyJqb2JfdGl0bGUiOiJEYXRhIEFuYWx5c3QiLCJodGlkb2...,https://encrypted-tbn0.gstatic.com/images?q=tb...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[]
2,2,2,Aeronautical Data Analyst,"Garmin International, Inc.","Olathe, KS",via Indeed,Overview:\n\nWe are seeking a full-time...\nAe...,"['18 hours ago', 'Full-time']",eyJqb2JfdGl0bGUiOiJBZXJvbmF1dGljYWwgRGF0YSBBbm...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,['sql']
3,3,3,Data Analyst - Consumer Goods - Contract to Hire,Upwork,Anywhere,via Upwork,Enthusiastic Data Analyst for processing sales...,"['12 hours ago', '15–25 an hour', 'Work from h...",eyJqb2JfdGl0bGUiOiJEYXRhIEFuYWx5c3QgLSBDb25zdW...,NaN,...,NaN,15–25,an hour,20.0,15.0,25.0,20.0,NaN,41600.0,"['powerpoint', 'excel', 'power_bi']"
4,4,4,Data Analyst | Workforce Management,Krispy Kreme,United States,via LinkedIn,Overview of Position\n\nThis position will be ...,"['7 hours ago', '90K–110K a year', 'Contractor']",eyJqb2JfdGl0bGUiOiJEYXRhIEFuYWx5c3QgfCBXb3JrZm...,https://encrypted-tbn0.gstatic.com/images?q=tb...,...,NaN,90K–110K,a year,100000.0,90000.0,110000.0,NaN,100000.0,100000.0,"['powerpoint', 'excel', 'outlook', 'word']"

In [46]:
df_cleaning['schedule_type']

0         Full-time
1         Full-time
2         Full-time
3        Contractor
4        Contractor
            ...
61948     Full-time
61949     Full-time
61950     Full-time
61951     Full-time
61952     Full-time
Name: schedule_type, Length: 61953, dtype: object

In [47]:
df_cleaning.drop(columns=['commute_time','thumbnail'],inplace=True)

In [52]:
df_cleaning.head()

,Unnamed: 0,index,title,company_name,location,via,description,extensions,job_id,posted_at,...,search_location,salary_pay,salary_rate,salary_avg,salary_min,salary_max,salary_hourly,salary_yearly,salary_standardized,description_tokens
0,0,0,Data Analyst,Meta,Anywhere,via LinkedIn,In the intersection of compliance and analytic...,"['15 hours ago', '101K–143K a year', 'Work fro...",eyJqb2JfdGl0bGUiOiJEYXRhIEFuYWx5c3QiLCJodGlkb2...,15 hours ago,...,United States,101K–143K,a year,122000.0,101000.0,143000.0,NaN,122000.0,122000.0,"['tableau', 'r', 'python', 'sql']"
1,1,1,Data Analyst,ATC,United States,via LinkedIn,Job Title: Entry Level Business Analyst / Prod...,"['12 hours ago', 'Full-time', 'Health insurance']",eyJqb2JfdGl0bGUiOiJEYXRhIEFuYWx5c3QiLCJodGlkb2...,12 hours ago,...,United States,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[]
2,2,2,Aeronautical Data Analyst,"Garmin International, Inc.","Olathe, KS",via Indeed,Overview:\n\nWe are seeking a full-time...\nAe...,"['18 hours ago', 'Full-time']",eyJqb2JfdGl0bGUiOiJBZXJvbmF1dGljYWwgRGF0YSBBbm...,18 hours ago,...,United States,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,['sql']
3,3,3,Data Analyst - Consumer Goods - Contract to Hire,Upwork,Anywhere,via Upwork,Enthusiastic Data Analyst for processing sales...,"['12 hours ago', '15–25 an hour', 'Work from h...",eyJqb2JfdGl0bGUiOiJEYXRhIEFuYWx5c3QgLSBDb25zdW...,12 hours ago,...,United States,15–25,an hour,20.0,15.0,25.0,20.0,NaN,41600.0,"['powerpoint', 'excel', 'power_bi']"
4,4,4,Data Analyst | Workforce Management,Krispy Kreme,United States,via LinkedIn,Overview of Position\n\nThis position will be ...,"['7 hours ago', '90K–110K a year', 'Contractor']",eyJqb2JfdGl0bGUiOiJEYXRhIEFuYWx5c3QgfCBXb3JrZm...,7 hours ago,...,United States,90K–110K,a year,100000.0,90000.0,110000.0,NaN,100000.0,100000.0,"['powerpoint', 'excel', 'outlook', 'word']"

In [50]:
df_cleaning.shape

(61953, 25)

In [53]:
df_cleaning['posted_at'].unique()

array(['15 hours ago', '12 hours ago', '18 hours ago', '7 hours ago',
       '20 hours ago', '17 hours ago', '8 hours ago', '21 hours ago',
       '14 hours ago', '22 hours ago', '23 hours ago', '10 hours ago',
       '19 hours ago', '9 hours ago', '11 hours ago', '13 hours ago',
       '16 hours ago', '6 hours ago', '24 hours ago', '4 hours ago',
       '3 hours ago', '5 hours ago', '2 hours ago', '53 minutes ago',
       '2 days ago', '3 days ago', nan, '24 days ago', '5 days ago',
       '1 day ago', '1 hour ago', '4 days ago', '8 days ago',
       '9 days ago', '10 days ago', '11 days ago', '20 days ago',
       '21 days ago', '19 days ago', '13 days ago', '14 days ago',
       '6 days ago', '7 days ago', '52 minutes ago', '16 days ago',
       '18 days ago', '15 days ago', '20 minutes ago', '12 days ago',
       '28 minutes ago', '56 minutes ago', '58 minutes ago',
       '42 minutes ago', '23 minutes ago', '24 minutes ago',
       '23 days ago', '26 minutes ago', '46 minutes ago',
       '36 minutes ago', '51 minutes ago', '15 minutes ago',
       '17 minutes ago', '33 minutes ago', '34 minutes ago',
       '19 minutes ago', '49 minutes ago', '59 minutes ago',
       '30 minutes ago', '57 minutes ago', '27 minutes ago',
       '50 minutes ago', '55 minutes ago', '17 days ago', '29 days ago',
       '22 days ago', '25 days ago', '27 days ago', '26 days ago',
       '28 days ago', '22 minutes ago', '25 minutes ago',
       '29 minutes ago', '41 minutes ago', '31 minutes ago',
       '5 minutes ago', '9 minutes ago', '12 minutes ago',
       '18 minutes ago', '37 minutes ago', '40 minutes ago',
       '43 minutes ago', '39 minutes ago', '44 minutes ago',
       '54 minutes ago', '60 minutes ago', '38 minutes ago',
       '47 minutes ago', '48 minutes ago', '4 minutes ago',
       '7 minutes ago', '8 minutes ago', '10 minutes ago',
       '13 minutes ago', '1 minute ago', '3 minutes ago',
       '11 minutes ago', '14 minutes ago', '16 minutes ago',
       '45 minutes ago', '35 minutes ago'], dtype=object)

In [55]:
df_cleaning['raw_posted_at']=df_cleaning['posted_at'].copy()

In [56]:
df_cleaning['raw_posted_at'] = (
    pd.to_datetime(df_cleaning['date_time'])
    - pd.to_timedelta(
        df_cleaning['posted_at'].str.replace(' ago', '', regex=False)
    )
)

In [64]:
df_cleaning['posted_at']=df_cleaning['raw_posted_at'].copy()

In [65]:
df_cleaning.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61953 entries, 0 to 61952
Data columns (total 26 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Unnamed: 0           61953 non-null  int64
 1   index                61953 non-null  int64
 2   title                61953 non-null  object
 3   company_name         61953 non-null  object
 4   location             61916 non-null  object
 5   via                  61944 non-null  object
 6   description          61953 non-null  object
 7   extensions           61953 non-null  object
 8   job_id               61953 non-null  object
 9   posted_at            61763 non-null  datetime64[ns]
 10  schedule_type        61707 non-null  object
 11  work_from_home       27980 non-null  object
 12  salary               10088 non-null  object
 13  search_term          61953 non-null  object
 14  date_time            61953 non-null  object
 15  search_location      61953 non-null  object
 16  salary_pay           10088 non-null  object
 17  salary_rate          10088 non-null  object
 18  salary_avg           10088 non-null  float64
 19  salary_min           9512 non-null   float64
 20  salary_max           9512 non-null   float64
 21  salary_hourly        5900 non-null   float64
 22  salary_yearly        4069 non-null   float64
 23  salary_standardized  10088 non-null  float64
 24  description_tokens   61953 non-null  object
 25  raw_posted_at        61763 non-null  datetime64[ns]
dtypes: datetime64[ns](2), float64(6), int64(2), object(16)
memory usage: 12.3+ MB

In [67]:
df_cleaning.drop(columns=['raw_posted_at'],inplace=True)

In [68]:
df_cleaning.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61953 entries, 0 to 61952
Data columns (total 25 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Unnamed: 0           61953 non-null  int64
 1   index                61953 non-null  int64
 2   title                61953 non-null  object
 3   company_name         61953 non-null  object
 4   location             61916 non-null  object
 5   via                  61944 non-null  object
 6   description          61953 non-null  object
 7   extensions           61953 non-null  object
 8   job_id               61953 non-null  object
 9   posted_at            61763 non-null  datetime64[ns]
 10  schedule_type        61707 non-null  object
 11  work_from_home       27980 non-null  object
 12  salary               10088 non-null  object
 13  search_term          61953 non-null  object
 14  date_time            61953 non-null  object
 15  search_location      61953 non-null  object
 16  salary_pay           10088 non-null  object
 17  salary_rate          10088 non-null  object
 18  salary_avg           10088 non-null  float64
 19  salary_min           9512 non-null   float64
 20  salary_max           9512 non-null   float64
 21  salary_hourly        5900 non-null   float64
 22  salary_yearly        4069 non-null   float64
 23  salary_standardized  10088 non-null  float64
 24  description_tokens   61953 non-null  object
dtypes: datetime64[ns](1), float64(6), int64(2), object(16)
memory usage: 11.8+ MB

In [69]:
df_cleaning['Posted_Year']=df_cleaning['posted_at'].dt.year

In [70]:
df_cleaning['Posted_Month']=df_cleaning['posted_at'].dt.month

In [71]:
df_cleaning.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61953 entries, 0 to 61952
Data columns (total 27 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Unnamed: 0           61953 non-null  int64
 1   index                61953 non-null  int64
 2   title                61953 non-null  object
 3   company_name         61953 non-null  object
 4   location             61916 non-null  object
 5   via                  61944 non-null  object
 6   description          61953 non-null  object
 7   extensions           61953 non-null  object
 8   job_id               61953 non-null  object
 9   posted_at            61763 non-null  datetime64[ns]
 10  schedule_type        61707 non-null  object
 11  work_from_home       27980 non-null  object
 12  salary               10088 non-null  object
 13  search_term          61953 non-null  object
 14  date_time            61953 non-null  object
 15  search_location      61953 non-null  object
 16  salary_pay           10088 non-null  object
 17  salary_rate          10088 non-null  object
 18  salary_avg           10088 non-null  float64
 19  salary_min           9512 non-null   float64
 20  salary_max           9512 non-null   float64
 21  salary_hourly        5900 non-null   float64
 22  salary_yearly        4069 non-null   float64
 23  salary_standardized  10088 non-null  float64
 24  description_tokens   61953 non-null  object
 25  Posted_Year          61763 non-null  float64
 26  Posted_Month         61763 non-null  float64
dtypes: datetime64[ns](1), float64(8), int64(2), object(16)
memory usage: 12.8+ MB

In [73]:
df_cleaning[['salary_avg','salary_min','salary_max','salary_hourly','salary_yearly','salary_standardized']].describe()

,salary_avg,salary_min,salary_max,salary_hourly,salary_yearly,salary_standardized
count,10088.000000,9512.000000,9512.000000,5900.000000,4069.000000,10088.000000
mean,42100.231239,34846.281874,50487.856787,40.539588,104115.406718,92289.425683
std,55893.993519,45843.034891,67366.522273,22.214540,36024.388492,43277.933820
min,7.250000,8.000000,10.000000,7.250000,29289.840000,15080.000000
25%,31.500000,19.520000,45.000000,23.265000,80000.180000,62400.000000
50%,60.000000,50.000000,75.000000,33.500000,96500.000000,88400.000000
75%,92500.000000,77000.000000,110000.000000,55.000000,120000.000000,117500.000000
max,550000.000000,450000.000000,850000.000000,300.000000,550000.000000,624000.000000

In [75]:
Q1 = df_cleaning['salary_yearly'].quantile(0.25)
Q3 = df_cleaning['salary_yearly'].quantile(0.75)

IQR = Q3 - Q1

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

print("Lower:", lower)
print("Upper:", upper)

outliers = df_cleaning[
    (df_cleaning['salary_yearly'] < lower) |
    (df_cleaning['salary_yearly'] > upper)
]

print(outliers.shape)
outliers['salary_yearly'].sort_values()

Q1: 80000.18
Q3: 120000.0
IQR: 39999.82000000001
Lower: 20000.449999999983
Upper: 179999.73
(142, 27)

48131    180000.0
36353    180000.0
36745    180000.0
2725     180211.2
2709     180211.2
           ...
38240    300000.0
8776     434500.0
26274    475000.0
26273    475000.0
3472     550000.0
Name: salary_yearly, Length: 142, dtype: float64

In [80]:
outliers[['title',  'salary_yearly']].sort_values(
    'salary_yearly',
    ascending=False
).tail(20)

                                           title  salary_yearly
36749              Secret Cleared Data Scientist       185000.0
38686                         Data Scientist NLP       185000.0
15816                        Senior Data Analyst       185000.0
20741   Staff Software Engineer, Data Governance       184500.0
22841  Lead Security Compliance Analyst (Remote)       184500.0
10112              Senior Data Analyst (Product)       184000.0
10111              Senior Data Analyst (Product)       184000.0
39246          Senior Data Scientist - Analytics       183000.0
51890               Senior Data Analyst (Remote)       182500.0
12821                         Data Analyst - new       182500.0
7065      Data Engineering Lead AWS & Databricks       182500.0
23288                        Data Analytics Lead       182439.0
11354                       Staff Data Scientist       182000.0
11353                       Staff Data Scientist       182000.0
26352                           PhD Statistician       181000.0
2709        Director - Data & Advanced Analytics       180211.2
2725        Director - Data & Advanced Analytics       180211.2
36745                   Principal Data Scientist       180000.0
36353                   Principal Data Scientist       180000.0
48131                        Lead Data Scientist       180000.0

In [81]:
df_cleaning.shape

(61953, 27)

In [82]:
df_cleaning.isna().sum().sort_values(ascending=False)

salary_yearly          57884
salary_hourly          56053
salary_min             52441
salary_max             52441
salary_rate            51865
salary_avg             51865
salary                 51865
salary_pay             51865
salary_standardized    51865
work_from_home         33973
schedule_type            246
Posted_Month             190
posted_at                190
Posted_Year              190
location                  37
via                        9
index                      0
title                      0
Unnamed: 0                 0
extensions                 0
job_id                     0
company_name               0
description                0
search_location            0
date_time                  0
search_term                0
description_tokens         0
dtype: int64

In [83]:
df_cleaning.duplicated().sum()

np.int64(0)

In [84]:
df_cleaning.dtypes

Unnamed: 0                      int64
index                           int64
title                          object
company_name                   object
location                       object
via                            object
description                    object
extensions                     object
job_id                         object
posted_at              datetime64[ns]
schedule_type                  object
work_from_home                 object
salary                         object
search_term                    object
date_time                      object
search_location                object
salary_pay                     object
salary_rate                    object
salary_avg                    float64
salary_min                    float64
salary_max                    float64
salary_hourly                 float64
salary_yearly                 float64
salary_standardized           float64
description_tokens             object
Posted_Year                   float64
Posted_Month                  float64
dtype: object

In [85]:
df_cleaning.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61953 entries, 0 to 61952
Data columns (total 27 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Unnamed: 0           61953 non-null  int64
 1   index                61953 non-null  int64
 2   title                61953 non-null  object
 3   company_name         61953 non-null  object
 4   location             61916 non-null  object
 5   via                  61944 non-null  object
 6   description          61953 non-null  object
 7   extensions           61953 non-null  object
 8   job_id               61953 non-null  object
 9   posted_at            61763 non-null  datetime64[ns]
 10  schedule_type        61707 non-null  object
 11  work_from_home       27980 non-null  object
 12  salary               10088 non-null  object
 13  search_term          61953 non-null  object
 14  date_time            61953 non-null  object
 15  search_location      61953 non-null  object
 16  salary_pay           10088 non-null  object
 17  salary_rate          10088 non-null  object
 18  salary_avg           10088 non-null  float64
 19  salary_min           9512 non-null   float64
 20  salary_max           9512 non-null   float64
 21  salary_hourly        5900 non-null   float64
 22  salary_yearly        4069 non-null   float64
 23  salary_standardized  10088 non-null  float64
 24  description_tokens   61953 non-null  object
 25  Posted_Year          61763 non-null  float64
 26  Posted_Month         61763 non-null  float64
dtypes: datetime64[ns](1), float64(8), int64(2), object(16)
memory usage: 12.8+ MB

In [86]:
df_cleaning.to_csv("job_market_cleaned.csv", index=False)